version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_PASS=kn
      - RABBITMQ_DEFAULT_USER=kn
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq-publisher:
    image: rabbitmq-publisher
    environment:
      RABBITMQ_HOST: rabbitmq
      PUBLISH_FREQUENCY: 5
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shipmentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shipmentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: kn
      SPRING_RABBITMQ_PASSWORD: kn
    depends_on:
      - rabbitmq
      - rabbitmq-publisher
      - postgres

volumes:
  postgres_data:
